### ISSUE TITLE
MG Design

### ISSUE THREAD

**Issue by Malavika-Srinivasan** [Malavika-Srinivasan/CAS741#30]
@smiths 

Hello Dr.Smith,

Can you please take a look at the uses hierarchy below and let me know if it is correct ?
[UsesHierarchy.pdf](https://github.com/Malavika-Srinivasan/CAS741/files/2568927/UsesHierarchy.pdf)

Thank you,
Malavika

**Comment by smiths** [comment]
@Malavika-Srinivasan,  your figure looks fine.  I would use a different shape for the external program, maybe an ellipse, instead of a rectangle.  You want to show that it isn't actually a module in your system, but something external.

I thought you might have a data structure module to store the newly created representation of the function?   Something like the CurveT module in the 2ME3 example that I discussed in class, or the FunctADT module in GlassBR.

**Comment by smiths** [comment]
My comments on the MG are given in 989141c.
