### ISSUE TITLE
MIS - Minor issues - typos, formatting, consistency, etc

### ISSUE THREAD

**Issue by bmaclach** [Malavika-Srinivasan/CAS741#34]
Here are some minor issues I found with the MIS:

- In the introduction section, there should be a space between "CFS" and "(C"
- In the introduction section, the variable n is referred to as 'n' and then as _n_. This notation should be consistent (probably change 'n' to _n_)
- Section 6,2 should have content, even if that content is just "Not applicable"
- There are extra horizontal lines at the bottom of the tables in Sections 6.3, 9.3, and 9.3.2
- In section 6.3.2, there should be a "-" in the "In" column
- In section 6.3, verifyDegree has no output, but in section 6.3.2 it has output
- In section 6.4.3, in the first assumption, the word "the" should not appear before "calling"
- In section 6.4.3, I think the first assumption is not necessary as it is covered by the third assumption
- In section 6.4.4, for the access programs with exceptions, "exc" should be italicized to be consistent with "out" in the other access programs
- In section 6.4.4, for loadInput's transition, there should not be a space between "_y_" and "."
- In section 6.4.4, for loadInput's exception, the logical or symbol (\lor in LaTeX) should be used instead of "OR"
- In section 6.4.4, for verifyDegree transition, it is enough to say "deg \in N" without "deg > 0" because all N are greater than 0 (same idea for the exception)
- In section 6.4.4, 7.4.4, and 8.4.4, sometimes you have "exception: None" but sometimes you have "exception: NA". These should be made consistent.
- In section 7.4.1, you say that "k is the number of sections". I think you should consider going into more detail there. What is a section? Is it the space between 2 data points? If so, isn't k just n - 1?
- In section 7.4.4, for interpBSpline, transition, item 2, the type of x should appear after the ":" 
- In section 7.4.4, for interpBSpline, transition, item 2, the formatting here is confusing. I'm not sure exactly what it should look like, but maybe "for k > 0." should be changed to "For k > 0,"? This looks like a loop, but then what is the upper bound on k? When does the loop end?
- I like the comments in Section 8.4.4, and I think they should appear in the actual text of the MIS.
- In section 8.4.4 "degVerify" is sometimes italicized and sometimes not. This should be made consistent
- In section 8.4.4, for evalReg output, I think _ynew_ should be _yNew_
- In section 9, the word "the" is missing before "user program".
- In section 9.4.4, for plotDataFit, transition, item 2, the arguments to plot should all be italicized (for consistency)
- In section 9.4.4, for plotDataFit, output, "Out" should be "_out_"(for consistency)
- The appendix can be removed since it is empty

**Comment by Malavika-Srinivasan** [comment]
@bmaclach 
Hi Brooks, 

Thanks for your detailed feedback. Please see my reply in bold below.

In the introduction section, there should be a space between "CFS" and "(C" - **Done**
In the introduction section, the variable n is referred to as 'n' and then as n. This notation should be consistent (probably change 'n' to n) - **Done**
Section 6,2 should have content, even if that content is just "Not applicable" - **I forgot to add Seq Services module. Added a place holder now.**
There are extra horizontal lines at the bottom of the tables in Sections 6.3, 9.3, and 9.3.2 - **Done**
In section 6.3.2, there should be a "-" in the "In" column - **Done**
In section 6.3, verifyDegree has no output, but in section 6.3.2 it has output - **Done**
In section 6.4.3, in the first assumption, the word "the" should not appear before "calling" - **Done**
In section 6.4.3, I think the first assumption is not necessary as it is covered by the third assumption - **I think both of them are necessary as it is possible that the user access the state variables by mistake.**
In section 6.4.4, for the access programs with exceptions, "exc" should be italicized to be consistent with "out" in the other access programs - **Done**
In section 6.4.4, for loadInput's transition, there should not be a space between "y" and "." - **Done**
In section 6.4.4, for loadInput's exception, the logical or symbol (\lor in LaTeX) should be used instead of "OR" - **Done**
In section 6.4.4, for verifyDegree transition, it is enough to say "deg \in N" without "deg > 0" because all N are greater than 0 (same idea for the exception) - **Yes, deg \in N is sufficient. Good catch.**
In section 6.4.4, 7.4.4, and 8.4.4, sometimes you have "exception: None" but sometimes you have "exception: NA". These should be made consistent. - **Done**
In section 7.4.1, you say that "k is the number of sections". I think you should consider going into more detail there. What is a section? Is it the space between 2 data points? If so, isn't k just n - 1? **This cannot be finalized without implementation. Now I have some part of implementation done and I can say that x will be of length n X m, where n is the number of data points and m is n-1 which is the number of sections.**
In section 7.4.4, for interpBSpline, transition, item 2, the type of x should appear after the ":" **Done**
In section 7.4.4, for interpBSpline, transition, item 2, the formatting here is confusing. I'm not sure exactly what it should look like, but maybe "for k > 0." should be changed to "For k > 0,"? This looks like a loop, but then what is the upper bound on k? When does the loop end? **Changes made, I missed adding that the loop ends at n, which is the number of data points.**
I like the comments in Section 8.4.4, and I think they should appear in the actual text of the MIS.
In section 8.4.4 "degVerify" is sometimes italicized and sometimes not. This should be made consistent - **Done**
In section 8.4.4, for evalReg output, I think ynew should be yNew **Done**
In section 9, the word "the" is missing before "user program".  **Done**
In section 9.4.4, for plotDataFit, transition, item 2, the arguments to plot should all be italicized (for consistency) - **Done**
In section 9.4.4, for plotDataFit, output, "Out" should be "out"(for consistency) - **Done**
The appendix can be removed since it is empty - **Done**

Thank you Brooks. I appreciate your feedback. Please see my changes here - 54b62e1


Malavika
