### ISSUE TITLE
MIS - Comments about notation

### ISSUE THREAD

**Issue by bmaclach** [Malavika-Srinivasan/CAS741#35]
Some question and comments about the notation used in the MIS:

- I think you should include the primitive type boolean in your table in section 4, and then when you later refer to booleans (section 6.4.1) just use the notation symbol B (\mathbb{B} in LaTeX)
- For conditional rules, you sometimes use \Rightarrow and sometimes use \Longrightarrow. Is there a difference in the meaning between the two? If not, they should be made consistent.
- In section 7.4.4 for interpHermite, for the y vector you introduce a notation where you have a superscript number in parentheses such as y<sub>0</sub><sup>(1)</sup>. What does this mean?
- When you specify the dimensions of an array, such as R<sup>n-1Xm</sup>, I think it would be more readable if you used \times in LaTeX instead of "X", or just use a comma
- The notation you use for quantifiers doesn't quite match up with Hoffman and Strooper or Gries and Schneider, which were the references we talked about in class. For example, in section 6.4.4 for verifyInput you have "\forall x \in t \land x \notin R".  I think this means that TypeError happens if _every_ x in t is not a real number, but I think what you really want is for the error to happen if _any_ x in t is not a real number, so you should use \exists instead of \forall. However I also do not recognize that specific notation, so maybe I'm wrong. Either way, you should specify in section 4 what notation you are using for quantifiers since it is not Hoffman and Strooper.

**Comment by bmaclach** [comment]
Forgot one:

- Throughout section 8.4.4 there is _x<sup>n</sup>_ and _x<sup>m</sup>_, which look like x to the power of n and m. I think these were intended to convey the size of _x_, so I think these should just say _x_, and then the type of _x_ should be specified, where the type includes the size (like how you did it in section 7.4.4)

**Comment by Malavika-Srinivasan** [comment]
1.  think you should include the primitive type boolean in your table in section 4, and then when you later refer to booleans (section 6.4.1) just use the notation symbol B (\mathbb{B} in LaTeX) - Done

2. For conditional rules, you sometimes use \Rightarrow and sometimes use \Longrightarrow. Is there a difference in the meaning between the two? If not, they should be made consistent. - They don't mean anything. Changes everything to \Longrightarrow

3. n section 7.4.4 for interpHermite, for the y vector you introduce a notation where you have a superscript number in parentheses such as y0(1). What does this mean? - The superscript represents the derivative. (1) means first derivative. I made an explicit note of it in the document as well.

4. When you specify the dimensions of an array, such as Rn-1Xm, I think it would be more readable if you used \times in LaTeX instead of "X", or just use a comma - changed to \times. Thanks.

5. The notation you use for quantifiers doesn't quite match up with Hoffman and Strooper or Gries and Schneider, which were the references we talked about in class. For example, in section 6.4.4 for verifyInput you have "\forall x \in t \land x \notin R". I think this means that TypeError happens if every x in t is not a real number, but I think what you really want is for the error to happen if any x in t is not a real number, so you should use \exists instead of \forall. However I also do not recognize that specific notation, so maybe I'm wrong. Either way, you should specify in section 4 what notation you are using for quantifiers since it is not Hoffman and Strooper. - I changed the specific instances to \exists. 

6. Throughout section 8.4.4 there is xn and xm, which look like x to the power of n and m. I think these were intended to convey the size of x, so I think these should just say x, and then the type of x should be specified, where the type includes the size (like how you did it in section 7.4.4) - Changes made.
