### ISSUE TITLE
[UnitVnVPlan Review] General Comments

### ISSUE THREAD

**Issue by hananezlitni** [Malavika-Srinivasan/CAS741#44]
Some general comments:

- I would add a road map for the document in the blurb before section 3 (at the top of page 1)
- At the end of line 1 in sub-section 3.1, “of” is repeated twice
- Missing period after the MIS document URL in line 4 in  sub-section 3.1
- There’s no need for the comma in line 3 of sub-section 3.2
- In line 6 of sub-section 3.2, “module” should be “modules”, similarly in the last line of the paragraph (end of line 8)
- In line 5 of sub-section 5.1.1, “… for CFS is associated” should be “… for CFS are associated”, since we’re talking about multiple constraints

**Comment by Malavika-Srinivasan** [comment]
@hananezlitni 

I would add a road map for the document in the blurb before section 3 (at the top of page 1)
- There is a road map of what is contained in this document.

At the end of line 1 in sub-section 3.1, “of” is repeated twice
- Thanks, corrected typo

Missing period after the MIS document URL in line 4 in sub-section 3.1
- Thanks, added period

There’s no need for the comma in line 3 of sub-section 3.2
- Yes, removed ,

In line 6 of sub-section 3.2, “module” should be “modules”, similarly in the last line of the paragraph (end of line 8)
- Changed

In line 5 of sub-section 5.1.1, “… for CFS is associated” should be “… for CFS are associated”, since we’re talking about multiple constraints
- Thanks, changed.

**Comment by Malavika-Srinivasan** [comment]
15d3d66
